export const FACILITIES = [
  { name: 'Projector', description: 'Ceiling or wall-mounted digital projector' },
  { name: 'Smart Board', description: 'Interactive smart whiteboard' },
  { name: 'Computers', description: 'Desktop computers for students' },
  { name: 'Internet', description: 'High-speed internet access' },
  { name: 'Audio System', description: 'Speakers and microphone system' },
  { name: 'Air Conditioning', description: 'Air-conditioned room' },
  { name: 'Power Backup', description: 'Uninterruptible power supply' },
  { name: 'Recording Equipment', description: 'Lecture recording equipment' },
  { name: 'Laboratory Equipment', description: 'Scientific laboratory apparatus' },
  { name: 'Whiteboard', description: 'Standard whiteboard' },
];

export const FACULTIES = [
  { name: 'Faculty of Computing and Informatics', code: 'FCI', description: 'Computer Science, Software Engineering and IT' },
  { name: 'Faculty of Engineering', code: 'FE', description: 'Electrical, Mechanical and Civil Engineering' },
  { name: 'Faculty of Business and Management', code: 'FBM', description: 'Business, Accounting and Finance' },
  { name: 'Faculty of Health Sciences', code: 'FHS', description: 'Nursing and Laboratory Sciences' },
  { name: 'Faculty of Education', code: 'FED', description: 'Education and Humanities' },
];

export const DEPARTMENTS = [
  { name: 'Computer Science', code: 'CS', facultyCode: 'FCI', preferredBuilding: 'C' },
  { name: 'Software Engineering', code: 'SE', facultyCode: 'FCI', preferredBuilding: 'C' },
  { name: 'Information Technology', code: 'IT', facultyCode: 'FCI', preferredBuilding: 'C' },
  { name: 'Electrical Engineering', code: 'EE', facultyCode: 'FE', preferredBuilding: 'B' },
  { name: 'Mechanical Engineering', code: 'ME', facultyCode: 'FE', preferredBuilding: 'B' },
  { name: 'Business Administration', code: 'BA', facultyCode: 'FBM', preferredBuilding: 'A' },
  { name: 'Accounting and Finance', code: 'AF', facultyCode: 'FBM', preferredBuilding: 'A' },
  { name: 'Nursing', code: 'NU', facultyCode: 'FHS', preferredBuilding: 'D' },
  { name: 'Medical Laboratory Science', code: 'MLS', facultyCode: 'FHS', preferredBuilding: 'D' },
  { name: 'Education', code: 'ED', facultyCode: 'FED', preferredBuilding: 'F' },
];

const lect = (staffNo: string, name: string, deptCode: string, title: string) => ({ staffNo, name, deptCode, title });

export const LECTURERS = [
  lect('STAFF-001', 'Dr. Amina Yusuf', 'CS', 'Senior Lecturer'),
  lect('STAFF-002', 'Prof. John Mwangi', 'CS', 'Professor'),
  lect('STAFF-003', 'Dr. Sarah Okafor', 'SE', 'Senior Lecturer'),
  lect('STAFF-004', 'Mr. David Kim', 'SE', 'Lecturer'),
  lect('STAFF-005', 'Dr. Grace Ndlovu', 'IT', 'Senior Lecturer'),
  lect('STAFF-006', 'Ms. Fatima Hassan', 'IT', 'Lecturer'),
  lect('STAFF-007', 'Dr. Peter Adebayo', 'EE', 'Senior Lecturer'),
  lect('STAFF-008', 'Prof. Linda Chen', 'EE', 'Professor'),
  lect('STAFF-009', 'Dr. Robert Smith', 'ME', 'Senior Lecturer'),
  lect('STAFF-010', 'Ms. Naledi Mokoena', 'ME', 'Lecturer'),
  lect('STAFF-011', 'Dr. Cynthia Wanjiku', 'BA', 'Senior Lecturer'),
  lect('STAFF-012', 'Prof. Samuel Otieno', 'BA', 'Professor'),
  lect('STAFF-013', 'Dr. Elizabeth Mensah', 'AF', 'Senior Lecturer'),
  lect('STAFF-014', 'Mr. Kwame Boateng', 'AF', 'Lecturer'),
  lect('STAFF-015', 'Dr. Maryam Bello', 'NU', 'Senior Lecturer'),
  lect('STAFF-016', 'Ms. Zainab Abubakar', 'NU', 'Lecturer'),
  lect('STAFF-017', 'Dr. James Otieno', 'MLS', 'Senior Lecturer'),
  lect('STAFF-018', 'Prof. Helen Muthoni', 'MLS', 'Professor'),
  lect('STAFF-019', 'Dr. Daniel Kariuki', 'ED', 'Senior Lecturer'),
  lect('STAFF-020', 'Ms. Agnes Chebet', 'ED', 'Lecturer'),
  lect('STAFF-021', 'Dr. Farouk Adeleke', 'CS', 'Lecturer'),
  lect('STAFF-022', 'Dr. Tunde Alabi', 'EE', 'Lecturer'),
  lect('STAFF-023', 'Dr. Priya Sharma', 'SE', 'Lecturer'),
  lect('STAFF-024', 'Mr. Brian Odhiambo', 'IT', 'Lecturer'),
  lect('STAFF-025', 'Dr. Carol Nyambura', 'AF', 'Senior Lecturer'),
  lect('STAFF-026', 'Mr. Victor Mwangi', 'ME', 'Lecturer'),
  lect('STAFF-027', 'Dr. Aisha Mohammed', 'NU', 'Senior Lecturer'),
  lect('STAFF-028', 'Mr. Eric Omondi', 'BA', 'Lecturer'),
  lect('STAFF-029', 'Dr. Ruth Achieng', 'MLS', 'Senior Lecturer'),
  lect('STAFF-030', 'Ms. Joyce Wairimu', 'ED', 'Lecturer'),
];

// classroom: roomCode, building, floor, capacity, roomType, accessibility, facilities[]
export const CLASSROOMS = [
  { roomCode: 'LT-101', building: 'A', floor: 1, capacity: 120, roomType: 'Lecture Hall', accessibility: 'Wheelchair', facilities: ['Projector', 'Internet', 'Air Conditioning', 'Audio System', 'Whiteboard'] },
  { roomCode: 'LT-102', building: 'A', floor: 1, capacity: 80, roomType: 'Lecture Hall', accessibility: 'Wheelchair', facilities: ['Projector', 'Internet', 'Air Conditioning', 'Audio System', 'Whiteboard'] },
  { roomCode: 'LT-103', building: 'A', floor: 1, capacity: 60, roomType: 'Lecture Hall', accessibility: 'None', facilities: ['Projector', 'Air Conditioning', 'Whiteboard'] },
  { roomCode: 'SR-104', building: 'A', floor: 1, capacity: 35, roomType: 'Seminar Room', accessibility: 'Wheelchair', facilities: ['Projector', 'Smart Board', 'Air Conditioning', 'Whiteboard'] },
  { roomCode: 'SR-105', building: 'A', floor: 2, capacity: 30, roomType: 'Seminar Room', accessibility: 'None', facilities: ['Projector', 'Whiteboard', 'Air Conditioning'] },
  { roomCode: 'LT-201', building: 'B', floor: 1, capacity: 150, roomType: 'Lecture Hall', accessibility: 'Wheelchair', facilities: ['Projector', 'Internet', 'Audio System', 'Air Conditioning', 'Whiteboard'] },
  { roomCode: 'LT-202', building: 'B', floor: 1, capacity: 100, roomType: 'Lecture Hall', accessibility: 'Wheelchair', facilities: ['Projector', 'Internet', 'Audio System', 'Whiteboard'] },
  { roomCode: 'LT-203', building: 'B', floor: 2, capacity: 75, roomType: 'Lecture Hall', accessibility: 'None', facilities: ['Projector', 'Whiteboard'] },
  { roomCode: 'LT-204', building: 'B', floor: 2, capacity: 90, roomType: 'Lecture Hall', accessibility: 'Wheelchair', facilities: ['Projector', 'Internet', 'Audio System', 'Air Conditioning', 'Smart Board'] },
  { roomCode: 'LT-205', building: 'B', floor: 2, capacity: 70, roomType: 'Lecture Hall', accessibility: 'None', facilities: ['Projector', 'Whiteboard', 'Air Conditioning'] },
  { roomCode: 'CL-301', building: 'C', floor: 1, capacity: 40, roomType: 'Computer Lab', accessibility: 'Wheelchair', facilities: ['Computers', 'Internet', 'Projector', 'Power Backup', 'Air Conditioning'] },
  { roomCode: 'CL-302', building: 'C', floor: 1, capacity: 45, roomType: 'Computer Lab', accessibility: 'None', facilities: ['Computers', 'Internet', 'Projector', 'Power Backup'] },
  { roomCode: 'CL-303', building: 'C', floor: 1, capacity: 50, roomType: 'Computer Lab', accessibility: 'Wheelchair', facilities: ['Computers', 'Internet', 'Projector', 'Air Conditioning', 'Smart Board'] },
  { roomCode: 'CL-304', building: 'C', floor: 2, capacity: 40, roomType: 'Computer Lab', accessibility: 'None', facilities: ['Computers', 'Internet', 'Projector', 'Power Backup', 'Recording Equipment'] },
  { roomCode: 'CL-305', building: 'C', floor: 2, capacity: 35, roomType: 'Computer Lab', accessibility: 'None', facilities: ['Computers', 'Internet', 'Projector'] },
  { roomCode: 'LB-401', building: 'D', floor: 1, capacity: 30, roomType: 'Laboratory', accessibility: 'None', facilities: ['Laboratory Equipment', 'Power Backup', 'Internet', 'Whiteboard'] },
  { roomCode: 'LB-402', building: 'D', floor: 1, capacity: 25, roomType: 'Laboratory', accessibility: 'None', facilities: ['Laboratory Equipment', 'Power Backup'] },
  { roomCode: 'LB-403', building: 'D', floor: 2, capacity: 30, roomType: 'Laboratory', accessibility: 'None', facilities: ['Laboratory Equipment', 'Internet', 'Power Backup', 'Whiteboard'] },
  { roomCode: 'LT-404', building: 'D', floor: 2, capacity: 110, roomType: 'Lecture Hall', accessibility: 'Wheelchair', facilities: ['Projector', 'Internet', 'Audio System', 'Whiteboard'] },
  { roomCode: 'LT-405', building: 'D', floor: 2, capacity: 85, roomType: 'Lecture Hall', accessibility: 'None', facilities: ['Projector', 'Whiteboard'] },
  { roomCode: 'LT-501', building: 'E', floor: 1, capacity: 200, roomType: 'Lecture Hall', accessibility: 'Wheelchair', facilities: ['Projector', 'Internet', 'Audio System', 'Air Conditioning', 'Whiteboard'] },
  { roomCode: 'LT-502', building: 'E', floor: 1, capacity: 130, roomType: 'Lecture Hall', accessibility: 'Wheelchair', facilities: ['Projector', 'Audio System', 'Whiteboard'] },
  { roomCode: 'LT-503', building: 'E', floor: 2, capacity: 95, roomType: 'Lecture Hall', accessibility: 'None', facilities: ['Projector', 'Whiteboard', 'Air Conditioning'] },
  { roomCode: 'EX-504', building: 'E', floor: 2, capacity: 300, roomType: 'Examination Hall', accessibility: 'Wheelchair', facilities: ['Air Conditioning', 'Power Backup', 'Internet'] },
  { roomCode: 'SR-601', building: 'F', floor: 1, capacity: 40, roomType: 'Seminar Room', accessibility: 'Wheelchair', facilities: ['Projector', 'Smart Board', 'Internet', 'Air Conditioning'] },
  { roomCode: 'SR-602', building: 'F', floor: 1, capacity: 25, roomType: 'Seminar Room', accessibility: 'None', facilities: ['Projector', 'Whiteboard'] },
  { roomCode: 'SR-603', building: 'F', floor: 2, capacity: 20, roomType: 'Seminar Room', accessibility: 'None', facilities: ['Projector', 'Smart Board'] },
  { roomCode: 'CN-604', building: 'F', floor: 2, capacity: 50, roomType: 'Conference Room', accessibility: 'Wheelchair', facilities: ['Projector', 'Audio System', 'Internet', 'Air Conditioning', 'Smart Board'] },
  { roomCode: 'LT-701', building: 'G', floor: 1, capacity: 65, roomType: 'Lecture Hall', accessibility: 'None', facilities: ['Projector', 'Whiteboard'] },
  { roomCode: 'CL-702', building: 'G', floor: 1, capacity: 30, roomType: 'Computer Lab', accessibility: 'None', facilities: ['Computers', 'Internet', 'Projector'] },
  { roomCode: 'LB-801', building: 'H', floor: 1, capacity: 25, roomType: 'Laboratory', accessibility: 'None', facilities: ['Laboratory Equipment', 'Power Backup', 'Internet'] },
  { roomCode: 'EX-802', building: 'H', floor: 1, capacity: 250, roomType: 'Examination Hall', accessibility: 'Wheelchair', facilities: ['Air Conditioning', 'Power Backup'] },
];

// course: code, name, deptCode, studentCount, creditHours, requiredRoomType, facilities[], lecturerIdx
export const COURSES = [
  { code: 'CSC101', name: 'Introduction to Programming', dept: 'CS', students: 120, credits: 4, roomType: 'Computer Lab', facilities: ['Computers', 'Internet'], lecturer: 'Dr. Amina Yusuf' },
  { code: 'CSC102', name: 'Data Structures and Algorithms', dept: 'CS', students: 110, credits: 4, roomType: 'Computer Lab', facilities: ['Computers', 'Internet'], lecturer: 'Prof. John Mwangi' },
  { code: 'CSC201', name: 'Database Systems', dept: 'CS', students: 90, credits: 3, roomType: 'Computer Lab', facilities: ['Computers', 'Internet'], lecturer: 'Dr. Farouk Adeleke' },
  { code: 'CSC202', name: 'Operating Systems', dept: 'CS', students: 100, credits: 3, roomType: 'Lecture Hall', facilities: ['Projector'], lecturer: 'Dr. Amina Yusuf' },
  { code: 'CSC301', name: 'Artificial Intelligence', dept: 'CS', students: 60, credits: 4, roomType: 'Computer Lab', facilities: ['Computers', 'Internet', 'Projector'], lecturer: 'Dr. Grace Ndlovu' },
  { code: 'SE101', name: 'Software Engineering Fundamentals', dept: 'SE', students: 85, credits: 3, roomType: 'Lecture Hall', facilities: ['Projector', 'Internet'], lecturer: 'Dr. Sarah Okafor' },
  { code: 'SE201', name: 'Web Application Development', dept: 'SE', students: 75, credits: 4, roomType: 'Computer Lab', facilities: ['Computers', 'Internet'], lecturer: 'Dr. Priya Sharma' },
  { code: 'SE202', name: 'Mobile Application Development', dept: 'SE', students: 70, credits: 4, roomType: 'Computer Lab', facilities: ['Computers', 'Internet'], lecturer: 'Mr. David Kim' },
  { code: 'SE301', name: 'Systems Analysis and Design', dept: 'SE', students: 55, credits: 3, roomType: 'Lecture Hall', facilities: ['Projector'], lecturer: 'Dr. Sarah Okafor' },
  { code: 'SE401', name: 'Capstone Project I', dept: 'SE', students: 40, credits: 3, roomType: 'Seminar Room', facilities: ['Projector'], lecturer: 'Mr. David Kim' },
  { code: 'IT101', name: 'Introduction to Information Technology', dept: 'IT', students: 130, credits: 3, roomType: 'Lecture Hall', facilities: ['Projector', 'Internet'], lecturer: 'Dr. Grace Ndlovu' },
  { code: 'IT201', name: 'Computer Networks', dept: 'IT', students: 80, credits: 4, roomType: 'Computer Lab', facilities: ['Computers', 'Internet'], lecturer: 'Mr. Brian Odhiambo' },
  { code: 'IT202', name: 'Cyber Security Fundamentals', dept: 'IT', students: 70, credits: 3, roomType: 'Computer Lab', facilities: ['Computers', 'Internet', 'Projector'], lecturer: 'Ms. Fatima Hassan' },
  { code: 'IT301', name: 'Cloud Computing', dept: 'IT', students: 60, credits: 4, roomType: 'Computer Lab', facilities: ['Computers', 'Internet'], lecturer: 'Ms. Fatima Hassan' },
  { code: 'IT401', name: 'IT Project Management', dept: 'IT', students: 45, credits: 3, roomType: 'Seminar Room', facilities: ['Projector'], lecturer: 'Dr. Grace Ndlovu' },
  { code: 'EE101', name: 'Circuit Analysis', dept: 'EE', students: 95, credits: 4, roomType: 'Laboratory', facilities: ['Laboratory Equipment'], lecturer: 'Dr. Peter Adebayo' },
  { code: 'EE201', name: 'Digital Electronics', dept: 'EE', students: 85, credits: 4, roomType: 'Laboratory', facilities: ['Laboratory Equipment', 'Power Backup'], lecturer: 'Prof. Linda Chen' },
  { code: 'EE202', name: 'Electromagnetics', dept: 'EE', students: 70, credits: 3, roomType: 'Lecture Hall', facilities: ['Projector'], lecturer: 'Dr. Tunde Alabi' },
  { code: 'EE301', name: 'Control Systems', dept: 'EE', students: 55, credits: 4, roomType: 'Laboratory', facilities: ['Laboratory Equipment'], lecturer: 'Prof. Linda Chen' },
  { code: 'EE401', name: 'Power Systems Engineering', dept: 'EE', students: 40, credits: 4, roomType: 'Lecture Hall', facilities: ['Projector', 'Audio System'], lecturer: 'Dr. Peter Adebayo' },
  { code: 'ME101', name: 'Engineering Mechanics', dept: 'ME', students: 100, credits: 4, roomType: 'Lecture Hall', facilities: ['Projector'], lecturer: 'Dr. Robert Smith' },
  { code: 'ME201', name: 'Thermodynamics', dept: 'ME', students: 80, credits: 4, roomType: 'Lecture Hall', facilities: ['Projector', 'Air Conditioning'], lecturer: 'Mr. Victor Mwangi' },
  { code: 'ME202', name: 'Fluid Mechanics', dept: 'ME', students: 75, credits: 3, roomType: 'Laboratory', facilities: ['Laboratory Equipment'], lecturer: 'Dr. Robert Smith' },
  { code: 'ME301', name: 'Machine Design', dept: 'ME', students: 50, credits: 4, roomType: 'Laboratory', facilities: ['Laboratory Equipment', 'Power Backup'], lecturer: 'Ms. Naledi Mokoena' },
  { code: 'BA101', name: 'Principles of Management', dept: 'BA', students: 140, credits: 3, roomType: 'Lecture Hall', facilities: ['Projector', 'Audio System'], lecturer: 'Dr. Cynthia Wanjiku' },
  { code: 'BA201', name: 'Marketing Management', dept: 'BA', students: 110, credits: 3, roomType: 'Lecture Hall', facilities: ['Projector'], lecturer: 'Prof. Samuel Otieno' },
  { code: 'BA202', name: 'Human Resource Management', dept: 'BA', students: 90, credits: 3, roomType: 'Lecture Hall', facilities: ['Projector', 'Internet'], lecturer: 'Mr. Eric Omondi' },
  { code: 'BA301', name: 'Strategic Management', dept: 'BA', students: 60, credits: 3, roomType: 'Seminar Room', facilities: ['Projector', 'Smart Board'], lecturer: 'Dr. Cynthia Wanjiku' },
  { code: 'AF101', name: 'Financial Accounting', dept: 'AF', students: 120, credits: 4, roomType: 'Lecture Hall', facilities: ['Projector'], lecturer: 'Dr. Elizabeth Mensah' },
  { code: 'AF201', name: 'Corporate Finance', dept: 'AF', students: 95, credits: 4, roomType: 'Lecture Hall', facilities: ['Projector', 'Internet'], lecturer: 'Dr. Carol Nyambura' },
  { code: 'AF202', name: 'Auditing and Assurance', dept: 'AF', students: 75, credits: 3, roomType: 'Lecture Hall', facilities: ['Projector'], lecturer: 'Mr. Kwame Boateng' },
  { code: 'AF301', name: 'Investment Analysis', dept: 'AF', students: 50, credits: 4, roomType: 'Seminar Room', facilities: ['Projector', 'Internet'], lecturer: 'Dr. Elizabeth Mensah' },
  { code: 'NU101', name: 'Foundations of Nursing', dept: 'NU', students: 110, credits: 4, roomType: 'Lecture Hall', facilities: ['Projector', 'Audio System'], lecturer: 'Dr. Maryam Bello' },
  { code: 'NU201', name: 'Medical-Surgical Nursing', dept: 'NU', students: 85, credits: 4, roomType: 'Laboratory', facilities: ['Laboratory Equipment', 'Power Backup'], lecturer: 'Dr. Aisha Mohammed' },
  { code: 'NU202', name: 'Pharmacology for Nurses', dept: 'NU', students: 80, credits: 3, roomType: 'Lecture Hall', facilities: ['Projector'], lecturer: 'Ms. Zainab Abubakar' },
  { code: 'NU301', name: 'Community Health Nursing', dept: 'NU', students: 55, credits: 3, roomType: 'Seminar Room', facilities: ['Projector', 'Whiteboard'], lecturer: 'Dr. Maryam Bello' },
  { code: 'MLS101', name: 'Introduction to Medical Laboratory Science', dept: 'MLS', students: 90, credits: 3, roomType: 'Laboratory', facilities: ['Laboratory Equipment'], lecturer: 'Dr. James Otieno' },
  { code: 'MLS201', name: 'Clinical Chemistry', dept: 'MLS', students: 70, credits: 4, roomType: 'Laboratory', facilities: ['Laboratory Equipment', 'Power Backup'], lecturer: 'Prof. Helen Muthoni' },
  { code: 'MLS202', name: 'Microbiology', dept: 'MLS', students: 65, credits: 4, roomType: 'Laboratory', facilities: ['Laboratory Equipment', 'Internet'], lecturer: 'Dr. Ruth Achieng' },
  { code: 'MLS301', name: 'Hematology', dept: 'MLS', students: 50, credits: 4, roomType: 'Laboratory', facilities: ['Laboratory Equipment'], lecturer: 'Dr. James Otieno' },
  { code: 'ED101', name: 'Educational Psychology', dept: 'ED', students: 100, credits: 3, roomType: 'Lecture Hall', facilities: ['Projector'], lecturer: 'Dr. Daniel Kariuki' },
  { code: 'ED201', name: 'Curriculum Development', dept: 'ED', students: 85, credits: 3, roomType: 'Lecture Hall', facilities: ['Projector', 'Internet'], lecturer: 'Ms. Agnes Chebet' },
  { code: 'ED202', name: 'Teaching Methods', dept: 'ED', students: 70, credits: 3, roomType: 'Seminar Room', facilities: ['Projector', 'Smart Board'], lecturer: 'Ms. Joyce Wairimu' },
  { code: 'ED301', name: 'Educational Technology', dept: 'ED', students: 55, credits: 4, roomType: 'Computer Lab', facilities: ['Computers', 'Internet', 'Projector'], lecturer: 'Dr. Daniel Kariuki' },
  { code: 'GED101', name: 'Communication Skills', dept: 'ED', students: 150, credits: 2, roomType: 'Lecture Hall', facilities: ['Projector', 'Audio System'], lecturer: 'Dr. Daniel Kariuki' },
  { code: 'GED102', name: 'Quantitative Skills', dept: 'CS', students: 140, credits: 2, roomType: 'Lecture Hall', facilities: ['Projector'], lecturer: 'Prof. John Mwangi' },
  { code: 'GED103', name: 'Critical Thinking', dept: 'ED', students: 130, credits: 2, roomType: 'Lecture Hall', facilities: ['Projector'], lecturer: 'Ms. Agnes Chebet' },
  { code: 'GED104', name: 'Ethics and Professionalism', dept: 'BA', students: 125, credits: 2, roomType: 'Lecture Hall', facilities: ['Projector'], lecturer: 'Prof. Samuel Otieno' },
  { code: 'GED105', name: 'Research Methodology', dept: 'MLS', students: 90, credits: 3, roomType: 'Lecture Hall', facilities: ['Projector', 'Internet'], lecturer: 'Prof. Helen Muthoni' },
  { code: 'GED106', name: 'Entrepreneurship', dept: 'AF', students: 110, credits: 2, roomType: 'Lecture Hall', facilities: ['Projector', 'Audio System'], lecturer: 'Dr. Carol Nyambura' },
];

export const TIME_SLOTS = [
  { day: 0, start: '08:00', end: '09:30', period: 'Morning 1' },
  { day: 0, start: '09:45', end: '11:15', period: 'Morning 2' },
  { day: 0, start: '11:30', end: '13:00', period: 'Midday' },
  { day: 0, start: '14:00', end: '15:30', period: 'Afternoon 1' },
  { day: 0, start: '15:45', end: '17:15', period: 'Afternoon 2' },
  { day: 1, start: '08:00', end: '09:30', period: 'Morning 1' },
  { day: 1, start: '09:45', end: '11:15', period: 'Morning 2' },
  { day: 1, start: '11:30', end: '13:00', period: 'Midday' },
  { day: 1, start: '14:00', end: '15:30', period: 'Afternoon 1' },
  { day: 1, start: '15:45', end: '17:15', period: 'Afternoon 2' },
  { day: 2, start: '08:00', end: '09:30', period: 'Morning 1' },
  { day: 2, start: '09:45', end: '11:15', period: 'Morning 2' },
  { day: 2, start: '11:30', end: '13:00', period: 'Midday' },
  { day: 2, start: '14:00', end: '15:30', period: 'Afternoon 1' },
  { day: 2, start: '15:45', end: '17:15', period: 'Afternoon 2' },
  { day: 3, start: '08:00', end: '09:30', period: 'Morning 1' },
  { day: 3, start: '09:45', end: '11:15', period: 'Morning 2' },
  { day: 3, start: '11:30', end: '13:00', period: 'Midday' },
  { day: 3, start: '14:00', end: '15:30', period: 'Afternoon 1' },
  { day: 3, start: '15:45', end: '17:15', period: 'Afternoon 2' },
  { day: 4, start: '08:00', end: '09:30', period: 'Morning 1' },
  { day: 4, start: '09:45', end: '11:15', period: 'Morning 2' },
  { day: 4, start: '11:30', end: '13:00', period: 'Midday' },
  { day: 4, start: '14:00', end: '15:30', period: 'Afternoon 1' },
  { day: 4, start: '15:45', end: '17:15', period: 'Afternoon 2' },
];

export const SEMESTERS = [
  { name: 'Semester 1 2025/2026', startDate: '2025-09-01', endDate: '2026-01-30', status: 'COMPLETED' },
  { name: 'Semester 2 2025/2026', startDate: '2026-02-02', endDate: '2026-06-30', status: 'ACTIVE' },
];

export const DEMO_USERS = [
  { name: 'System Administrator', email: 'admin@example.com', password: 'Admin@123', role: 'SUPER_ADMIN', department: null },
];
